import type { FactorDefinition } from "./types";

/**
 * Static registry of contextual factors considered by the Cognitive Engine.
 * rawValue / weight / confidence are populated at runtime by WeightsEngine.
 */
export const FACTORS: FactorDefinition[] = [
  // —— Economy ——
  {
    id: "economy_gdp_growth",
    name: "Crescita PIL",
    category: "economy",
    source: "ISTAT",
    description: "Variazione del PIL rispetto all'anno precedente",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "economy_unemployment",
    name: "Tasso di Disoccupazione",
    category: "economy",
    source: "ISTAT",
    description: "Percentuale di disoccupati sul totale della forza lavoro",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "economy_inflation",
    name: "Inflazione",
    category: "economy",
    source: "ISTAT",
    description: "Variazione annua dell'indice dei prezzi al consumo",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "economy_income",
    name: "Reddito disponibile",
    category: "economy",
    source: "ISTAT",
    description: "Indice di reddito disponibile delle famiglie (proxy BES)",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "economy_consumption",
    name: "Consumi delle famiglie",
    category: "economy",
    source: "ISTAT",
    description: "Dinamica dei consumi (proxy da soddisfazione economica BES)",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "economy_investment",
    name: "Clima degli investimenti",
    category: "economy",
    source: "ISTAT",
    description: "Proxy di clima economico / investimenti sul territorio",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },

  // —— Polls (main parties) ——
  {
    id: "polls_average_pd",
    name: "Sondaggio Medio PD",
    category: "polls",
    source: "Sondaggi",
    description: "Media ponderata dei sondaggi per il PD negli ultimi 30 giorni",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "polls_average_fdi",
    name: "Sondaggio Medio FdI",
    category: "polls",
    source: "Sondaggi",
    description: "Media ponderata dei sondaggi per FdI negli ultimi 30 giorni",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "polls_average_m5s",
    name: "Sondaggio Medio M5S",
    category: "polls",
    source: "Sondaggi",
    description: "Media ponderata dei sondaggi per M5S negli ultimi 30 giorni",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "polls_average_lega",
    name: "Sondaggio Medio Lega",
    category: "polls",
    source: "Sondaggi",
    description: "Media ponderata dei sondaggi per la Lega negli ultimi 30 giorni",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "polls_average_fi",
    name: "Sondaggio Medio FI",
    category: "polls",
    source: "Sondaggi",
    description: "Media ponderata dei sondaggi per Forza Italia negli ultimi 30 giorni",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "polls_average_av",
    name: "Sondaggio Medio Azione/IV",
    category: "polls",
    source: "Sondaggi",
    description: "Media ponderata dei sondaggi per Azione/Italia Viva",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },

  // —— Social (mock until API integration) ——
  {
    id: "social_sentiment_pd",
    name: "Sentiment Social PD",
    category: "social",
    source: "Twitter",
    description: "Sentiment medio conversazioni social sul PD (mock)",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "social_sentiment_fdi",
    name: "Sentiment Social FdI",
    category: "social",
    source: "Twitter",
    description: "Sentiment medio conversazioni social su FdI (mock)",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "social_volume_candidate",
    name: "Volume conversazioni candidato",
    category: "social",
    source: "Twitter",
    description: "Volume relativo delle menzioni del candidato (mock)",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "social_sentiment_national",
    name: "Sentiment Social Nazionale",
    category: "social",
    source: "Twitter",
    description: "Sentiment aggregato conversazioni politiche nazionali (mock)",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },

  // —— News (mock) ——
  {
    id: "news_tone_pd",
    name: "Tono notizie PD",
    category: "news",
    source: "GoogleNews",
    description: "Tono mediatico medio sul PD (mock)",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "news_tone_fdi",
    name: "Tono notizie FdI",
    category: "news",
    source: "GoogleNews",
    description: "Tono mediatico medio su FdI (mock)",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "news_coverage_candidate",
    name: "Copertura mediatica candidato",
    category: "news",
    source: "GoogleNews",
    description: "Quota di copertura mediatica del candidato (mock)",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "news_tone_national",
    name: "Tono mediatico nazionale",
    category: "news",
    source: "GoogleNews",
    description: "Tono aggregato del dibattito pubblico (mock)",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },

  // —— Historical ——
  {
    id: "historical_last_share_pd",
    name: "Ultimo risultato PD",
    category: "historical",
    source: "Ministero",
    description: "Quota PD nell'ultima elezione disponibile sul territorio",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "historical_last_share_fdi",
    name: "Ultimo risultato FdI",
    category: "historical",
    source: "Ministero",
    description: "Quota FdI nell'ultima elezione disponibile sul territorio",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "historical_last_share_m5s",
    name: "Ultimo risultato M5S",
    category: "historical",
    source: "Ministero",
    description: "Quota M5S nell'ultima elezione disponibile sul territorio",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "historical_comune_trend",
    name: "Tendenza storica del comune",
    category: "historical",
    source: "Ministero",
    description: "Stabilità del voto locale (bassa volatilità → alto)",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },

  // —— Demographic ——
  {
    id: "demographic_avg_age",
    name: "Età media",
    category: "demographic",
    source: "ISTAT",
    description: "Proxy demografico età (normalizzato)",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "demographic_education",
    name: "Livello di istruzione",
    category: "demographic",
    source: "ISTAT",
    description: "Quota popolazione con istruzione terziaria (proxy BES)",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
  {
    id: "demographic_density",
    name: "Densità abitativa",
    category: "demographic",
    source: "ISTAT",
    description: "Proxy densità urbana (normalizzata)",
    rawValue: null,
    weight: 0,
    confidence: 0,
    trend: "stable",
    trendMagnitude: 0,
  },
];

export function getFactorById(id: string): FactorDefinition | undefined {
  return FACTORS.find((f) => f.id === id);
}

export function factorsByCategory(
  category: FactorDefinition["category"],
): FactorDefinition[] {
  return FACTORS.filter((f) => f.category === category);
}
